CREATE TABLE IF NOT EXISTS "product_embeddings" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"product_id" BIGINT NOT NULL,
	"embedding" VECTOR(64) NOT NULL,
	"model_version" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE UNIQUE INDEX ""
ON "product_embeddings" ("product_id", "model_version");

CREATE TABLE IF NOT EXISTS "sales" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" BIGINT NOT NULL,
	"total_price" DECIMAL(10,2) NOT NULL CHECK(CHECK (total_price >= 0)),
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "sale_items" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"sale_id" BIGINT NOT NULL,
	"product_id" BIGINT NOT NULL,
	"quantity" INTEGER NOT NULL CHECK(CHECK (quantity > 0)),
	"unit_price" DECIMAL(10,2) NOT NULL CHECK(CHECK (unit_price >= 0)),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "products" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"sku" VARCHAR(100) NOT NULL UNIQUE,
	"name" VARCHAR(255) NOT NULL,
	"description" VARCHAR(500),
	"price" DECIMAL(10,2) NOT NULL CHECK(CHECK (price >= 0)),
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "product_categories" (
	"product_id" BIGINT NOT NULL,
	"category_id" BIGINT NOT NULL
);

CREATE INDEX ""
ON "product_categories" ("product_id", "category_id");

CREATE TABLE IF NOT EXISTS "categories" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL UNIQUE,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "users" (
	"id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"first_name" VARCHAR(255) NOT NULL,
	"last_name" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"password_hash" VARCHAR(255) NOT NULL,
	"role" VARCHAR(50) NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	"updated_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

ALTER TABLE "sales"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sale_items"
ADD FOREIGN KEY("sale_id") REFERENCES "sales"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "sale_items"
ADD FOREIGN KEY("product_id") REFERENCES "products"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "product_categories"
ADD FOREIGN KEY("product_id") REFERENCES "products"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "product_categories"
ADD FOREIGN KEY("category_id") REFERENCES "categories"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "product_embeddings"
ADD FOREIGN KEY("product_id") REFERENCES "products"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

INSERT INTO products (
    sku,
    name,
    description,
    price,
    created_at,
    updated_at
) VALUES
      ('IPHONE-15', 'iPhone 15', 'Latest Apple smartphone', 999.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      ('GALAXY-S24', 'Samsung Galaxy S24', 'Latest Samsung smartphone', 899.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      ('MACBOOK-PRO-16', 'MacBook Pro 16"', 'Apple laptop', 2499.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      ('DELL-XPS-13', 'Dell XPS 13', 'Dell ultrabook', 1299.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);