-- ShopWise - schema relationnel du catalogue et des ventes.
-- Les donnees de demonstration sont dans app_eval/src/main/resources/data.sql.
CREATE TABLE IF NOT EXISTS users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name VARCHAR(255) NOT NULL,
 last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 role VARCHAR(50) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS categories (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sku VARCHAR(100) NOT NULL UNIQUE,
 name VARCHAR(255) NOT NULL UNIQUE, description VARCHAR(500), price DECIMAL(10,2) NOT NULL CHECK (price >= 0),
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS product_categories (
 product_id BIGINT NOT NULL, category_id BIGINT NOT NULL, PRIMARY KEY (product_id, category_id),
 FOREIGN KEY (product_id) REFERENCES products(id), FOREIGN KEY (category_id) REFERENCES categories(id));
CREATE TABLE IF NOT EXISTS sales (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL,
 total_price DECIMAL(10,2) NOT NULL CHECK (total_price >= 0), created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS sale_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sale_id BIGINT NOT NULL, product_id BIGINT NOT NULL,
 quantity INTEGER NOT NULL CHECK (quantity > 0), unit_price DECIMAL(10,2) NOT NULL CHECK (unit_price >= 0),
 FOREIGN KEY (sale_id) REFERENCES sales(id), FOREIGN KEY (product_id) REFERENCES products(id));
